export const cities = [
  "guarulhos",
  "jundiai",
  "limeira",
  "lorena",
  "maua",
  "osasco",
  "piracicaba",
  "ribeirao-preto",
  "rio-claro",
  "santa-gertrudes",
  "santo-andre",
  "santos",
  "sao-bernardo-do-campo",
  "sao-caetano-do-sul",
  "sao-paulo",
  "taubate",
];
